const DEFAULT_PRODUCTS=[
{id:1,name:"Premium Men's T-Shirt",cat:"Male",price:599,img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=700"},
{id:2,name:"Elegant Women's Dress",cat:"Female",price:999,img:"https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=700"},
{id:3,name:"Kids Casual Wear",cat:"Children",price:499,img:"https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=700"},
{id:4,name:"Remote Control Toy Car",cat:"Toys",price:799,img:"https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=700"},
{id:5,name:"Wireless Earbuds",cat:"Electronics",price:1299,img:"https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=700"},
{id:6,name:"Smart Watch",cat:"Electronics",price:1799,img:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=700"}];
const UPI_ID="mrsunnykumar@ptaxis";
const STORE_NAME="SBmart";
let products=[],cart=JSON.parse(localStorage.getItem("sbmart_cart")||"[]"),current="All";
const productsEl=document.getElementById("products");
const saveCart=()=>localStorage.setItem("sbmart_cart",JSON.stringify(cart));
async function loadProducts(){try{products=await (await fetch('/api/products')).json();render()}catch(e){toast('Could not load products')}}
function cat(c,el){current=c;document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));el.classList.add("active");render()}
function render(){const q=(document.getElementById("search")?.value||"").toLowerCase();const a=products.filter(p=>(current==="All"||p.cat===current)&&p.name.toLowerCase().includes(q));if(!productsEl)return;document.getElementById("result").textContent=a.length+" products";productsEl.innerHTML=a.map((p,i)=>`<article class="card" style="animation-delay:${i*45}ms"><div class="pic"><img src="${p.img}" loading="lazy" onerror="this.src='https://placehold.co/600x600?text=SBmart'"></div><p class="cat">${p.cat}</p><h3>${p.name}</h3><div class="price">₹${Number(p.price).toLocaleString('en-IN')}</div><button class="add" onclick="add(${p.id})">Add to Cart</button></article>`).join('')||'<p>No products found.</p>'}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({...p,qty:1});saveCart();updateCount();toast('✓ Product added to cart')}
function updateCount(){const n=cart.reduce((s,x)=>s+x.qty,0),el=document.getElementById('cartCount');if(el)el.textContent=n}
function cartTotal(){return cart.reduce((s,x)=>s+x.price*x.qty,0)}
function openCart(){document.getElementById('cartModal').style.display='block';let sum=0;document.getElementById('cartItems').innerHTML=cart.map((p,i)=>{sum+=p.price*p.qty;return `<div class="row"><img src="${p.img}"><div class="grow"><b>${p.name}</b><br><small>₹${p.price.toLocaleString('en-IN')} × ${p.qty}</small></div><div class="qty"><button onclick="changeQty(${i},-1)">−</button><b>${p.qty}</b><button onclick="changeQty(${i},1)">+</button></div><button class="remove" onclick="removeItem(${i})">×</button></div>`}).join('')||'<p>Your cart is empty.</p>';document.getElementById('total').textContent=sum.toLocaleString('en-IN')}
function changeQty(i,d){cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);saveCart();updateCount();openCart()}function removeItem(i){cart.splice(i,1);saveCart();openCart();updateCount()}function closeCart(){document.getElementById('cartModal').style.display='none'}
function openPayment(){if(!cart.length)return toast('Cart is empty');closeCart();document.getElementById('payModal').style.display='block';const amount=cartTotal();document.getElementById('payAmount').textContent=amount.toLocaleString('en-IN');const uri=`upi://pay?pa=${encodeURIComponent(UPI_ID)}&pn=${encodeURIComponent('SBmart')}&am=${amount.toFixed(2)}&cu=INR&tn=${encodeURIComponent('SBmart Order')}`;const qr=document.getElementById('qrcode');qr.innerHTML='';new QRCode(qr,{text:uri,width:210,height:210,correctLevel:QRCode.CorrectLevel.M});document.getElementById('upiId').textContent=UPI_ID}
function closePay(){document.getElementById('payModal').style.display='none'}
async function confirmOrder(){const utr=document.getElementById('utr').value.trim(),name=document.getElementById('customerName').value.trim(),mobile=document.getElementById('customerMobile').value.trim(),address=document.getElementById('customerAddress').value.trim();if(!name||!mobile||!address)return toast('Name, mobile and delivery address are required');if(!/^\d{10}$/.test(mobile))return toast('Enter a valid 10-digit mobile number');if(!utr)return toast('Please enter UTR / Transaction ID');try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:{name,mobile,address},items:cart,total:cartTotal(),utr})});const x=await r.json();if(!r.ok)throw Error(x.error);cart=[];saveCart();updateCount();closePay();['utr','customerName','customerMobile','customerAddress'].forEach(id=>document.getElementById(id).value='');toast('✓ Order '+x.orderId+' submitted for verification')}catch(e){toast('Order submission failed')}}
function toast(msg){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
window.addEventListener('load',()=>{setTimeout(()=>document.getElementById('loader')?.classList.add('hide'),650);loadProducts();updateCount()});
